hwi_oauth:
  firewall_names: [main]
  fosub:
    username_iterations: 30
    properties:
      facebook: facebook_id
  resource_owners:
    facebook:
      type: facebook
      client_id: '%env(resolve:FACEBOOK_CLIENT_ID)%'
      client_secret: '%env(resolve:FACEBOOK_SECRET)%'
      infos_url: "https://graph.facebook.com/me?fields=id,name,email"
      options:
        csrf: true